### ISSUE TITLE
Uncaught TypeError: Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by yriveiro** [NikhilKalige/git-log#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.9.5
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'position' of undefined

```
At /Users/yriveiro/.atom/packages/git-log/lib/gitgraph.js:185

TypeError: Cannot read property 'position' of undefined
  at GitGraph.lines (/Users/yriveiro/.atom/packages/git-log/lib/gitgraph.js:185:27)
  at GitGraph.render (/Users/yriveiro/.atom/packages/git-log/lib/gitgraph.js:214:27)
  at new GitGraph (/Users/yriveiro/.atom/packages/git-log/lib/gitgraph.js:17:20)
  at GitLogView.parser (/Users/yriveiro/.atom/packages/git-log/lib/git-log-view.js:82:17)
  at GitLogView.log_callback (/Users/yriveiro/.atom/packages/git-log/lib/git-log-view.js:63:10)
  at /Users/yriveiro/.atom/packages/git-log/lib/git-log-view.js:45:18
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1068:12)

```

### Commands

```
  3x -1:04.8 core:backspace (atom-text-editor.editor.mini)
     -1:04.0 core:move-down (atom-text-editor.editor.mini)
     -1:03.5 core:confirm (atom-text-editor.editor.mini)
     -1:03.2 git-history:show-file-history (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:57.6 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:57.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:54.3 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:50.8 core:confirm (atom-text-editor.editor.mini)
     -0:50.8 git-log:show (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:42.4 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:40.7 core:backspace (atom-text-editor.editor.mini)
  5x -0:38.4 core:move-down (atom-text-editor.editor.mini)
     -0:37.2 core:confirm (atom-text-editor.editor.mini)
     -0:37.1 git-history:show-file-history (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -0:35.1 core:move-down (atom-text-editor.editor.mini)
     -0:34.3 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "emmet",
      "autocomplete",
      "go-plus",
      "Zen",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/yriveiro/Development/github"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-cli-diff, v0.6.4
atom-jshint, v1.5.0
atom-lint, v0.20.1
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v0.3.2
color-picker, v1.4.4
docblockr, v0.5.8
editor-stats, v0.16.0
file-icons, v1.4.8
git-history, v1.2.0
git-log, v0.2.0
git-tab-status, v1.5.3
language-jade, v0.3.0
linter, v0.10.1
linter-php, v0.0.11
minimap, v3.5.6
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
omni-ruler, v0.3.1
phpunit, v1.0.9
phpunit-snippets, v0.1.0
pretty-json, v0.3.2
script, v2.16.0
seti-syntax, v0.2.1
space-tab, v0.1.0
travis-ci-status, v0.11.2
vim-mode, v0.30.0
zentabs, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by Apokly** [comment]
Hey,

I would like to know if there were some updates about this ticket ?
Still have same issue on Linux Ubuntu.

thank you.

**Comment by 20after4** [comment]
@Apokly My pull request fixes this issue, it's related to color codes in the output from the `git log` command.

**Comment by ihorsavka** [comment]
have same issue
