### ISSUE TITLE
Can't close the git log tab.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [NikhilKalige/git-log#56]
Hello

When I try to close the git log tab, I get the following error:

```
TypeError: Cannot read property 'dispose' of undefined
 at /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:28
 at Set.forEach (native)
 at CompositeDisposable.module.exports.CompositeDisposable.dispose (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
 at tabs-tab.module.exports.TabView.destroy (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-view.js:194:14)
 at TabBarView.module.exports.TabBarView.removeTabForItem (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:364:15)
 at /usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:174:24
 at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
 at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:379:20)
 at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:442:16)
 at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:419:12)
 at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:602:35)
 at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/usr/share/atom/resources/app.asar/src/workspace.js:641:21)
 at atom-workspace.atom.commands.add.core:close (/usr/share/atom/resources/app.asar/src/workspace-element.js:314:30)
 at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
 at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
 at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
 at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
 at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)
```

After this the tab is completely stuck and I can never close it again without closing the entire window. Opening git log again spawns another tab that then has the same problem.

Thanks in advance

**Comment by yoongkang** [comment]
Can confirm this on Atom 1.0 too.

**Comment by alexbuzzbee** [comment]
This is parallel with [atom/tabs's issue 183](https://github.com/atom/tabs/issues/183).
