### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by kmassada** [NikhilKalige/git-log#59]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.81.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25

TypeError: Cannot read property 'dispose' of undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:28
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
  at tabs-tab.module.exports.TabView.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:194:14)
  at TabBarView.module.exports.TabBarView.removeTabForItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:364:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:174:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:379:20)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:442:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  8x -2:08.2.0 core:backspace (div.terminal)
     -2:04.9.0 core:confirm (div.terminal)
     -1:56.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:54.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:54.4.0 git-plus:log (atom-text-editor.editor)
     -1:50.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:48.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:48.3.0 git-log:show (atom-text-editor.editor)
     -1:46.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:46 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:25.5.0 settings-view:open (div.git-log)
     -0:48.4.0 core:move-right (atom-text-editor#git-log.fontScale.editor.mini.is-focused)
  3x -0:47.8.0 core:backspace (atom-text-editor#git-log.fontScale.editor.mini.is-focused)
     -0:41.4.0 core:confirm (div.settings-view.pane-item)
     -0:36.5.0 core:backspace (atom-text-editor#git-log.fontScale.editor.mini.is-focused)
     -0:27.4.0 core:confirm (atom-text-editor#git-log.fontFamily.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
change-case, v0.6.0
docblockr, v0.7.2
emmet, v2.3.11
git-log, v0.4.1
git-plus, v5.2.2
language-blade, v0.14.0
laravel, v0.7.0
linter, v1.1.0
linter-csslint, v0.0.14
linter-erb, v0.1.1
linter-jshint, v0.1.7
linter-pep8, v0.2.0
linter-tidy, v1.0.1
linter-write-good, v0.5.0
minimap, v4.10.1
seti-ui, v0.7.1
term2, v0.9.10

# Dev
No dev packages
```

**Comment by HKiOnline** [comment]
I have ran into the same exact issue. The same repro steps apply.

OS: Linux Mint 17.1 Rebecca.
Atom: 1.0
