### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by TriMoon** [NikhilKalige/git-log#84]
I am opening a **fresh issue** of #49, to attract attention to it.
Because #49 has been closed since it started and has had many other reports since then but the issue stayed closed without a fix.
That said;

## BUG REPORT ##
[Enter steps to reproduce:]

1. Go in a directory that has no git tracking yet
2. Enter at console: `git init --separate-git-dir=/gitrepos/xxxx --shared=group`
  Take note that `/gitrepos/xxxx` is any existing directory you want the git administrative files to be kept in...
3. Press `CTRL+F5` to reload the atom window in case you executed the above step inside a terminal emulator inside the Atom Window like i use.
  Otherwise start your Atom Editor with the directory you just initialized git in.
4. Press `CTRL+SHIFT+P` to bring up the command menu.
5. Select "Git Log Show"

**Atom**: 1.35.0-beta0 x64
**Electron**: 2.0.16
**OS**: Debian GNU/Linux
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package 0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /home/<username>/.atom/packages/git-log/lib/logparser.js:116

TypeError: Cannot read property 'split' of null
    at parse_git_log (/packages/git-log/lib/logparser.js:116:21)
    at GitLogView.parser (/packages/git-log/lib/git-log-view.js:117:16)
    at GitLogView.log_callback (/packages/git-log/lib/git-log-view.js:69:10)
    at /packages/git-log/lib/git-log-view.js:50:18
    at o (/usr/share/atom-beta/resources/app/static/<embedded>:14:1039005)
    at e.bufferStream (/usr/share/atom-beta/resources/app/static/<embedded>:14:1039093)
    at Socket.e.on (/usr/share/atom-beta/resources/app/static/<embedded>:14:1037761)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -5:02.8.0 intentions:highlight (input.hidden-input)
     -5:02.2.0 command-palette:toggle (input.hidden-input)
     -4:57.9.0 core:confirm (input.hidden-input)
     -4:57.9.0 git-log:show (input.hidden-input)
     -4:55.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-json-editor 0.4.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-minify 0.8.0 
atomic-management 0.3.1 
bezier-curve-editor 0.7.2 
busy-signal 2.0.0 
color-picker 2.3.0 
docblockr 0.13.7 
editorconfig 2.2.2 
file-icons 2.1.29 
git-log 0.4.1 
gitlab-integration 0.4.8 
intentions 1.1.5 
language-babel 2.85.0 
language-vue 0.24.0 
linter 2.3.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-autohider 1.6.0 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-linter 2.2.1 
pigments 0.40.2 
platformio-ide-terminal 2.9.0 
project-manager 3.3.6 
vuejs2-snippets 1.1.0 
```

**Comment by JABowie** [comment]
I have this issue as well

**Comment by ryter** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [git-log](https://github.com/nikhilkalige/git-log) package 0.4.1


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At C:\Users\ryter\.atom\packages\git-log\lib\logparser.js:116

TypeError: Cannot read property 'split' of null
    at parse_git_log (/packages/git-log/lib/logparser.js:116:21)
    at GitLogView.parser (/packages/git-log/lib/git-log-view.js:117:16)
    at GitLogView.log_callback (/packages/git-log/lib/git-log-view.js:69:10)
    at /packages/git-log/lib/git-log-view.js:50:18
    at o (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1032937)
    at t.bufferStream (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1033091)
    at Socket.e.on (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:1031693)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -4:31.6.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
  3x -4:29 core:backspace (input.hidden-input)
  4x -4:21.9.0 core:move-down (input.hidden-input)
     -4:20.3.0 core:confirm (input.hidden-input)
     -4:20.3.0 git-log:show (ul.list-inline.tab-bar.inset-panel)
  2x -4:12.9.0 command-palette:toggle (input.hidden-input)
  4x -2:19.3.0 core:move-down (input.hidden-input)
     -2:16.1.0 core:confirm (input.hidden-input)
     -2:16.1.0 git-log:show (ul.list-inline.tab-bar.inset-panel)
     -1:43 intentions:highlight (input.hidden-input)
     -1:42.6.0 command-palette:toggle (input.hidden-input)
  2x -1:39.3.0 core:move-down (input.hidden-input)
     -1:38.4.0 core:confirm (input.hidden-input)
     -1:38.4.0 git-log:show (input.hidden-input)
  3x -1:32.4.0 core:backspace (input.hidden-input)
     -1:30.1.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
editorconfig 2.4.0 
emmet 2.4.3 
git-log 0.4.1 
intentions 1.1.5 
language-dots 0.0.4 
language-rainmeter 1.7.4 
language-vue 0.24.0 
linter 2.3.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
oceanic-reef-syntax 0.9.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
```

**Comment by bobmacks** [comment]
+1

**Comment by Healseyn** [comment]
+1

**Comment by adeguzman-mtph** [comment]
+1
